sonar.projectKey=nadavpeisik_price-tracker
sonar.organization=nadavpeisik

sonar.sources=backend/src/main/java,scraper/main.py
sonar.tests=backend/src/test/java,scraper/tests

sonar.java.binaries=backend/target/classes
sonar.java.source=21

sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml
sonar.python.coverage.reportPaths=scraper/coverage.xml
sonar.python.version=3.12

sonar.exclusions=**/generated/**,**/target/**,**/.venv/**,**/node_modules/**
