-- app_user: application identity (epic #241, issue #243).
--
-- Identity is the pair (issuer, sub) — the only stable key an OIDC provider guarantees. Email is a
-- mutable, reassignable attribute and raw sub alone collides across providers, so neither is ever a
-- key; a provider migration is a relink of (issuer, sub), not a data migration. uq_app_user_identity
-- is the lookup path for token → user resolution (#245) and the guard against a concurrent
-- first-login double-insert.
--
-- display_currency is a preference, not money: nullable (null = "no preference, use the app
-- default"). Validation belongs to the write path (DisplayCurrencyResolver) — which codes are
-- convertible depends on the runtime FX-rate snapshot, which a migration cannot freeze.

CREATE TABLE app_user (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issuer varchar(255) NOT NULL,
    sub varchar(255) NOT NULL,
    email varchar(255),
    display_currency varchar(3),
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT uq_app_user_identity UNIQUE (issuer, sub)
);

-- Same audit-column contract as product/tracked_item (V12): no DEFAULT now() — @PrePersist stamps
-- it, and a hand-written insert must choose a time — and immutable at the database, reusing V12's
-- trigger function.
CREATE TRIGGER trg_app_user_created_at_immutable
BEFORE UPDATE ON app_user
FOR EACH ROW EXECUTE FUNCTION forbid_created_at_change();

-- Backfill: the single existing user, inserted unconditionally so the tenancy join table (#244)
-- has a deterministic target on every database. The (issuer, sub) pair is a temporary placeholder
-- under the reserved .invalid TLD — no real IdP can issue it — relinked by a later migration once
-- the Auth0 tenant exists. Email stays NULL until a real login supplies it.
INSERT INTO app_user (issuer, sub, created_at)
VALUES ('https://auth0-tenant-pending.invalid/', 'nadav', now());
