-- user_tracked_item: the tenancy join table (epic #241, issue #244).
--
-- The catalog stays shared — a URL is scraped once however many users watch it — so per-user
-- state (hidden, notifications, when added) lives here. Surrogate id because the dashboard pages
-- by keyset over (added_at, id). notify_enabled, not notify: NOTIFY is a Postgres keyword.
--
-- Both FKs cascade: a catalog delete takes its associations along, an account delete must not
-- orphan rows. JPA mirrors neither — user-facing removal is an unlink, deleting this row only.
CREATE TABLE user_tracked_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    tracked_item_id bigint NOT NULL REFERENCES tracked_item (id) ON DELETE CASCADE,
    hidden boolean NOT NULL DEFAULT false,
    notify_enabled boolean NOT NULL DEFAULT true,
    added_at timestamp with time zone NOT NULL,
    CONSTRAINT uq_user_tracked_item UNIQUE (user_id, tracked_item_id)
);

-- "Who watches this listing?" — the cascade above and Phase 3 fan-out. Postgres does not index
-- the referencing side of an FK (V10), and the unique index leads with user_id.
CREATE INDEX idx_user_tracked_item_item ON user_tracked_item (tracked_item_id);

-- The dashboard's access path (#226, #246): one user's visible listings, newest first, keyset over
-- (added_at, id). Partial because hidden rows never appear on that page. The notification
-- counterpart waits for its query (Phase 3).
CREATE INDEX idx_user_tracked_item_dashboard
ON user_tracked_item (user_id, added_at DESC, id DESC)
WHERE hidden = false;

-- Backfill every existing listing to the single V15 user. added_at copies tracked_item.created_at
-- rather than now(): it is the "recently added" sort key (#226), and a migration-day stamp would
-- tie every row. A missing V15 row becomes a NOT NULL violation, so the migration fails loudly
-- instead of inserting nothing.
INSERT INTO user_tracked_item (user_id, tracked_item_id, added_at)
SELECT
    (
        SELECT u.id FROM app_user AS u
        WHERE u.issuer = 'https://auth0-tenant-pending.invalid/' AND u.sub = 'nadav'
    ) AS user_id,
    ti.id AS tracked_item_id,
    ti.created_at AS added_at
FROM tracked_item AS ti;
