-- user_product: product-level membership (epic #241, issue #246).
--
-- V16 keyed tenancy on the listing; its first consumer found that is the wrong grain. A user tracks a
-- PRODUCT and wants every shop the catalog has for it, including shops other users add later, so a
-- per-listing key would need fan-out on every track and would leave rows behind on removal. One row
-- here means "user U tracks product P".
CREATE TABLE user_product (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    product_id bigint NOT NULL REFERENCES product (id) ON DELETE CASCADE,
    added_at timestamp with time zone NOT NULL,
    CONSTRAINT uq_user_product UNIQUE (user_id, product_id)
);

-- Postgres does not index the referencing side of an FK (V10), and the unique constraint's index
-- leads with user_id, so neither covers the cascade or "who tracks this product?".
CREATE INDEX idx_user_product_product ON user_product (product_id);

-- Backfill: every product, not just the ones V16 linked — anything tracked or created since #244 has
-- no V16 row, and empty products never had one. added_at comes from product.created_at, which V12 set
-- to the earliest listing, so a MIN over the V16 rows would order identically. The bare scalar
-- subquery is the guard: two app_user rows error, zero violates NOT NULL. It matches on nothing else
-- because the dev bootstrap may already have relinked V15's placeholder (issuer, sub).
INSERT INTO user_product (user_id, product_id, added_at)
SELECT
    (SELECT u.id FROM app_user AS u) AS user_id,
    p.id AS product_id,
    p.created_at AS added_at
FROM product AS p;

-- No writer for hidden/notify_enabled ever existed, so every V16 row is a default: nothing to keep.
DROP TABLE user_tracked_item;
