-- invitation: invite-only registration (epic #241, issue #249).
--
-- The identity provider authenticates; this table decides whether an identity may hold an account.
-- An authenticated (issuer, sub) with no app_user row redeems an invitation by its VERIFIED email
-- claim, and the redemption provisions the row. Email is the match key here and only here (V15: it is
-- never an identity), so a row holds the normalized spelling and nothing else about the person.
CREATE TABLE invitation (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Normalized: trimmed, lower-cased.
    email varchar(255) NOT NULL,
    -- NULL = hand-inserted bootstrap: a fresh database has no admin to invite the first one.
    invited_by bigint REFERENCES app_user (id) ON DELETE SET NULL,
    created_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    redeemed_at timestamp with time zone,
    redeemed_by bigint REFERENCES app_user (id) ON DELETE SET NULL,
    -- The bootstrap row is typed by hand; a mixed-case INSERT would never match and never conflict.
    CONSTRAINT ck_invitation_email_normalized CHECK (email = lower(btrim(email)))
);

-- "An email is invited or it is not": one OPEN row per email. Expiry is not in the predicate (now()
-- is not immutable); re-inviting supersedes the open row itself, so this settles only the admin race.
CREATE UNIQUE INDEX uq_invitation_open_email
ON invitation (email) WHERE redeemed_at IS NULL AND revoked_at IS NULL;

-- Same audit-column contract as app_user (V15), reusing V12's trigger function.
CREATE TRIGGER trg_invitation_created_at_immutable
BEFORE UPDATE ON invitation
FOR EACH ROW EXECUTE FUNCTION forbid_created_at_change();

-- V15's placeholder identity: no identity provider can issue it. Where the dev bootstrap relinked it
-- this matches nothing. On a fresh database the account should not exist, or the seeder would track
-- its fixtures for an account nobody can log in as; the first account now arrives through an
-- invitation. Where it was never relinked but V17 backfilled memberships onto it, those cascade away
-- (catalog untouched): nobody could reach them anyway.
DELETE FROM app_user
WHERE issuer = 'https://auth0-tenant-pending.invalid/' AND sub = 'nadav';
