-- hidden_listing: one user hides one shop under a product they track (epic #241, issue #250).
--
-- Membership is product-level (V17): tracking a URL shows every shop the catalog has for that
-- product. Not wanting to see one of them is an exception to that default, so it is a row here,
-- and only here. Presence is the whole state: a row means "hidden", no row means "visible", and
-- there is no flag column to keep in step with it. The parent is the MEMBERSHIP, not the user, so
-- "remove from my dashboard" (deleting the user_product row) cascades every hide away and a later
-- re-track starts clean. The listing side cascades too: a catalog delete takes its hides along.
-- Nothing to backfill; no writer existed before this migration.
CREATE TABLE hidden_listing (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_product_id bigint NOT NULL REFERENCES user_product (id) ON DELETE CASCADE,
    tracked_item_id bigint NOT NULL REFERENCES tracked_item (id) ON DELETE CASCADE,
    CONSTRAINT uq_hidden_listing UNIQUE (user_product_id, tracked_item_id)
);

-- Postgres does not index the referencing side of an FK (V10), and the unique constraint's index
-- leads with user_product_id, so neither covers the tracked_item cascade.
CREATE INDEX idx_hidden_listing_item ON hidden_listing (tracked_item_id);
