-- Baseline schema for PriceHunt.
-- Captured from dev Postgres 17.9 prior to Flyway adoption.
-- On existing DBs this never runs (baseline-on-migrate=true).
-- On fresh DBs it recreates the schema previously managed by ddl-auto=update.
--
-- The fk<hash> constraint names below are Hibernate-generated. Preserved as-is
-- so the existing dev DB (which already has these names) validates cleanly.

CREATE TABLE product (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description varchar(255),
    name varchar(255) NOT NULL
);

CREATE TABLE tracked_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_checked timestamp with time zone,
    shop_name varchar(255),
    url varchar(255),
    product_id bigint,
    CONSTRAINT fk4fbtcg07w6q2y3olq22vidfgs FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE price_record (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    available boolean NOT NULL,
    currency varchar(255),
    extraction_source varchar(255),
    price numeric(19,4) NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    tracked_item_id bigint NOT NULL,
    CONSTRAINT fk3kuc5fg4mov7uu1dt2eyx7f4e FOREIGN KEY (tracked_item_id) REFERENCES tracked_item(id),
    CONSTRAINT price_record_extraction_source_check
        CHECK (extraction_source IN ('STRUCTURED', 'SNIPPET', 'FULLTEXT'))
);

CREATE INDEX idx_price_record_item_timestamp
    ON price_record (tracked_item_id, "timestamp" DESC);

CREATE TABLE exchange_rate (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    as_of date NOT NULL,
    quote varchar(3) NOT NULL,
    rate numeric(19,8) NOT NULL,
    CONSTRAINT uq_exchange_rate_quote_as_of UNIQUE (quote, as_of)
);

CREATE INDEX idx_exchange_rate_as_of
    ON exchange_rate (as_of DESC);
