-- Baseline schema for PriceHunt.
-- Captured from dev Postgres 17.9 prior to Flyway adoption.
-- On existing DBs this never runs (baseline-on-migrate=true).
-- On fresh DBs it recreates the schema previously managed by ddl-auto=update.

CREATE TABLE product (
    id bigint NOT NULL,
    description character varying(255),
    name character varying(255) NOT NULL
);

ALTER TABLE product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY product
    ADD CONSTRAINT product_pkey PRIMARY KEY (id);


CREATE TABLE tracked_item (
    id bigint NOT NULL,
    last_checked timestamp(6) with time zone,
    shop_name character varying(255),
    url character varying(255),
    product_id bigint
);

ALTER TABLE tracked_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME tracked_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY tracked_item
    ADD CONSTRAINT tracked_item_pkey PRIMARY KEY (id);

ALTER TABLE ONLY tracked_item
    ADD CONSTRAINT fk4fbtcg07w6q2y3olq22vidfgs FOREIGN KEY (product_id) REFERENCES product(id);


CREATE TABLE price_record (
    id bigint NOT NULL,
    available boolean NOT NULL,
    currency character varying(255),
    extraction_source character varying(255),
    price numeric(19,4) NOT NULL,
    "timestamp" timestamp(6) with time zone NOT NULL,
    tracked_item_id bigint NOT NULL,
    CONSTRAINT price_record_extraction_source_check CHECK (((extraction_source)::text = ANY ((ARRAY['STRUCTURED'::character varying, 'SNIPPET'::character varying, 'FULLTEXT'::character varying])::text[])))
);

ALTER TABLE price_record ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME price_record_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY price_record
    ADD CONSTRAINT price_record_pkey PRIMARY KEY (id);

ALTER TABLE ONLY price_record
    ADD CONSTRAINT fk3kuc5fg4mov7uu1dt2eyx7f4e FOREIGN KEY (tracked_item_id) REFERENCES tracked_item(id);

CREATE INDEX idx_price_record_item_timestamp
    ON price_record USING btree (tracked_item_id, "timestamp" DESC);


CREATE TABLE exchange_rate (
    id bigint NOT NULL,
    as_of date NOT NULL,
    quote character varying(3) NOT NULL,
    rate numeric(19,8) NOT NULL
);

ALTER TABLE exchange_rate ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME exchange_rate_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY exchange_rate
    ADD CONSTRAINT exchange_rate_pkey PRIMARY KEY (id);

ALTER TABLE ONLY exchange_rate
    ADD CONSTRAINT uq_exchange_rate_quote_as_of UNIQUE (quote, as_of);

CREATE INDEX idx_exchange_rate_as_of
    ON exchange_rate USING btree (as_of DESC);
