-- Audit log for @Scheduled job executions. Each run gets one scheduled_job_run row;
-- per-item detail (e.g. each TrackedItem touched by PriceCheckScheduler) goes in
-- scheduled_job_run_item. FX refresh has no per-item granularity (single network
-- fetch), so it produces a run row only.
--
-- Status enum matches com.np.pricehunt.backend.domain.JobStatus. Items only ever
-- carry SUCCESS or FAILED — RUNNING/PARTIAL are run-level states.

CREATE TABLE scheduled_job_run (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_name varchar(64) NOT NULL,
    started_at timestamp with time zone NOT NULL,
    finished_at timestamp with time zone,
    status varchar(16) NOT NULL,
    items_processed integer NOT NULL DEFAULT 0,
    items_succeeded integer NOT NULL DEFAULT 0,
    items_failed integer NOT NULL DEFAULT 0,
    error_summary text,
    correlation_id varchar(64),
    CONSTRAINT scheduled_job_run_status_check
        CHECK (status IN ('RUNNING', 'SUCCESS', 'PARTIAL', 'FAILED'))
);

CREATE INDEX idx_scheduled_job_run_name_started
    ON scheduled_job_run (job_name, started_at DESC);

CREATE INDEX idx_scheduled_job_run_started
    ON scheduled_job_run (started_at DESC);

CREATE TABLE scheduled_job_run_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_run_id bigint NOT NULL,
    label text NOT NULL,
    status varchar(16) NOT NULL,
    duration_ms integer,
    error_message text,
    CONSTRAINT fk_scheduled_job_run_item_run
        FOREIGN KEY (job_run_id) REFERENCES scheduled_job_run(id) ON DELETE CASCADE,
    CONSTRAINT scheduled_job_run_item_status_check
        CHECK (status IN ('SUCCESS', 'FAILED'))
);

-- Full FK index: needed for ON DELETE CASCADE lookups (Postgres does not auto-index
-- FK referencing columns, unlike MySQL) and for drilling "show me items for run X".
CREATE INDEX idx_scheduled_job_run_item_run
    ON scheduled_job_run_item (job_run_id);

-- Partial index: items are ~95% SUCCESS in steady state. Indexing only failures
-- keeps the "failed items" dashboard query cheap and avoids index updates on every
-- successful scrape insert. JPA @Index cannot declare partial predicates — this
-- index lives only in Flyway DDL, not on the entity.
CREATE INDEX idx_scheduled_job_run_item_failed
    ON scheduled_job_run_item (job_run_id)
    WHERE status = 'FAILED';
