-- Auto shop-name detection (issue #33).
--
-- tracked_item.shop_name_source records WHICH tier produced an item's shop name, so a later
-- refresh never downgrades a better name (rank: MAPPING > DETECTED > HOST_FALLBACK). Nullable:
-- legacy rows predate detection and resolve lazily on their next refresh. Matches
-- com.np.pricehunt.backend.domain.ShopNameSource.
--
-- shop_name_mapping is the domain -> display_name table: curated marketplace seeds AND
-- auto-learned names, keyed on the PSL registrable domain. origin (CURATED | LEARNED) distinguishes
-- the two so the self-healing upsert (ShopNameMappingRepository.upsertLearned) never overwrites a
-- curated row. The UNIQUE(domain) constraint is the conflict target for that ON CONFLICT upsert.

ALTER TABLE tracked_item ADD COLUMN shop_name_source varchar(32);

ALTER TABLE tracked_item
    ADD CONSTRAINT tracked_item_shop_name_source_check
    CHECK (shop_name_source IN ('MAPPING', 'DETECTED', 'HOST_FALLBACK'));

CREATE TABLE shop_name_mapping (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain varchar(255) NOT NULL,
    display_name varchar(255) NOT NULL,
    origin varchar(32) NOT NULL,
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT uq_shop_name_mapping_domain UNIQUE (domain),
    CONSTRAINT shop_name_mapping_origin_check CHECK (origin IN ('CURATED', 'LEARNED'))
);

-- Curated marketplace/platform seeds: a marketplace domain resolves to the platform name, never a
-- third-party seller (seller attribution is tracked separately, #129). Keyed on registrable domain;
-- extend TLD variants as needed (issue #33 out-of-scope note).
INSERT INTO shop_name_mapping (domain, display_name, origin) VALUES
    ('amazon.com',     'Amazon',     'CURATED'),
    ('amazon.co.uk',   'Amazon',     'CURATED'),
    ('amazon.de',      'Amazon',     'CURATED'),
    ('ebay.com',       'eBay',       'CURATED'),
    ('ksp.co.il',      'KSP',        'CURATED'),
    ('aliexpress.com', 'AliExpress', 'CURATED'),
    ('walmart.com',    'Walmart',    'CURATED');
