-- Failure-first scrape-attempt audit (issue #131). One row per FAILED extraction or REJECTED
-- validation only — SUCCESS and the deterministic STRUCTURED-success tier are NOT recorded (they are
-- reproducible and add no regression-corpus value). Captures the exact LLM input so
-- "old input -> new prompt/model -> diff PriceInfo" replay is possible.
--
-- Enum columns are varchar+CHECK (matching scheduled_job_run / price_record.availability_status, not
-- native PG enums) so adding a value stays a normal transactional migration.

CREATE TABLE scrape_attempt (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Historical id with NO foreign key (deliberate): this is an append-only evidence table whose
    -- whole point is to survive deletion of the tracked_item it came from. A hard FK would (a) fail
    -- the best-effort audit insert if the item is deleted in the window between the scrape failure and
    -- the record write — losing exactly the failure we most want — and (b) null the id on delete,
    -- destroying forensic context. So we keep the id even after the item is gone.
    tracked_item_id   bigint,
    url               text NOT NULL,
    extraction_source varchar(16) NOT NULL,
    outcome           varchar(24) NOT NULL,
    failure_code      varchar(32) NOT NULL,  -- stable, low-cardinality; Grafana/queries group on this
    failure_detail    text,                  -- dynamic specifics (blocked reason, model, summarized exception, prior price)
    llm_input         text,                  -- exact text fed to the LLM (snippet / filtered innerText); null for STRUCTURED/BLOCKED
    prompt_version    varchar(32),           -- only when an LLM ran (SNIPPET/FULLTEXT); else null
    model_name        varchar(255),          -- only when an LLM ran; else null
    content_hash      varchar(64),           -- SHA-256(raw evidence); null for BLOCKED/STRUCTURED (no text)
    llm_input_hash    varchar(64),           -- SHA-256(exact LLM input); null for STRUCTURED/BLOCKED
    extraction_config_hash varchar(64),      -- SHA-256(output schema + options); a separate axis from prompt_version/model_name; null when no LLM ran
    correlation_id    varchar(255),          -- soft link to scheduled_job_run (MDC); deliberately not a FK
    retention_until   timestamp with time zone NOT NULL,
    created_at        timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT scrape_attempt_source_check  CHECK (extraction_source IN ('STRUCTURED','SNIPPET','FULLTEXT','BLOCKED')),
    CONSTRAINT scrape_attempt_outcome_check CHECK (outcome IN ('EXTRACTION_FAILED','VALIDATION_REJECTED')),
    CONSTRAINT scrape_attempt_failure_code_check CHECK (failure_code IN (
        'BLOCKED','EMPTY_INPUT','MALFORMED_LLM_OUTPUT','EXTRACTION_ERROR',
        'PRICE_NON_POSITIVE','NULL_PRICE','NULL_CURRENCY','DELTA_EXCEEDED'))
);

-- Drill-down "attempts for this item" + (no FK, so this is purely a query index).
CREATE INDEX idx_scrape_attempt_item ON scrape_attempt (tracked_item_id);

-- Purge driver: the daily job deletes WHERE retention_until < now().
CREATE INDEX idx_scrape_attempt_retention ON scrape_attempt (retention_until);

-- Grafana $__timeFilter(created_at) time-series panels.
CREATE INDEX idx_scrape_attempt_created_at ON scrape_attempt (created_at DESC);

-- Regression-corpus dedup / "find all attempts that fed a given LLM input". Partial: most rows have a
-- hash, but a BLOCKED/STRUCTURED row does not — skip them. JPA @Index can't express the predicate, so
-- this index lives only here, not on the entity.
CREATE INDEX idx_scrape_attempt_llm_input_hash ON scrape_attempt (llm_input_hash)
    WHERE llm_input_hash IS NOT NULL;
