apiVersion: 1
datasources:
  - name: PriceHuntPostgres
    uid: pricehunt-postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      database: ${POSTGRES_DB}
      sslmode: disable
      postgresVersion: 1700
    isDefault: true
    editable: false
